version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API=https://cwnotes.store/api
      - NEXT_PUBLIC_DOMAIN=https://cwnotes.ru
    restart: unless-stopped